### ISSUE TITLE
Set up indyrb.org on github pages

### ISSUE THREAD

**Issue by rreinhardt9** [indyrb/indyrb.github.io#1]
### Deploy Octopress to GitHub pages site.

@unixmonkey we'll need to set up a new repo named "indyrb.github.io" and then it will deploy to pages automatically from that repo. Looks like I don't have permissions to create a new repo, so maybe could you do that? Once we have that, I'll clone what we have in the current repo and deploy it into the new one.

**Comment by unixmonkey** [comment]
Cool. I've renamed the repo, so you can either change the remote name (edit .git/config) on your end, or clone again.

I've also given you (and the whole indyrb_website team) admin access to create/change repos.

Let me know if I'm missing anything else.

**Comment by rreinhardt9** [comment]
@unixmonkey @jbrowning , The branches in the repo have been renamed after the deploy... the old master is the new source so that the code for the site could live in master. Whatever is in master automatically gets deployed to the GitHub pages site. I left notes on how to get started with the new setup on your machines in the [readme on the source branch](https://github.com/indyrb/indyrb.github.io/blob/source/README.markdown). If you go to [indyrb.github.io](http://indyrb.github.io), you'll see what is currently in master. Yay!

**Comment by jbrowning** [comment]
Pretty slick. :+1: Thanks @rreinhardt9.
