### ISSUE TITLE
Sep 2010 Meetup Videos are missing

### ISSUE THREAD

**Issue by jbrowning** [indyrb/indyrb.github.io#2]
Getting a 404 for these:
- http://podcast.404dev.com/episodes/006-Anthony_Panozzo-Zsh_vs_Bash_Deathmatch.m4v
- http://podcast.404dev.com/episodes/007-Dave_Christiansen-Career-saving_advice.m4v
- http://podcast.404dev.com/episodes/008-Dave_Christiansen-Creating_a_plugin.m4v
- http://podcast.404dev.com/episodes/009-Matt_Gordon-Ruby_News.m4v

/cc @unixmonkey

**Comment by unixmonkey** [comment]
Thanks for noticing! I've updated the file names on the server.
